# Generated by Django 5.2.4 on 2025-07-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_created_at_item_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventory',
            field=models.CharField(default='0', max_length=13),
        ),
    ]
