# Generated by Django 5.2.4 on 2025-07-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(db_index=True, max_length=13, unique=True),
        ),
    ]
